import pyautogui
import webbrowser as wb
import time
wb.open("web.whatsapp.com")
time.sleep(30)
for i in range(1000):
    pyautogui.press("T")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("enter")
    pyautogui.press("b")
    pyautogui.press("enter")
    pyautogui.press("l")
    pyautogui.press("enter")
    pyautogui.press("e")
    pyautogui.press("enter")
    pyautogui.press("w")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("enter")
    pyautogui.press("p")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("enter")
    pyautogui.press("s")
    pyautogui.press("enter")
    pyautogui.press("l")
    pyautogui.press("enter")
    pyautogui.press("e")
    pyautogui.press("enter")
    pyautogui.press("k")
    pyautogui.press("enter")
    pyautogui.press("e")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("enter")
    pyautogui.press("a")
    pyautogui.press("enter")
